### ISSUE TITLE
IProjectorState uses reserved MSSQL keyword

### ISSUE THREAD

**Issue by MarcusChamberlain** [liquidprojections/LiquidProjections.NHibernate#13]
The interface IProjectorState uses a property called "Checkpoint". This is a reserved keyword in MSSQL server (https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017) and causes an error when NHibernate tries to create the ProjectorState table:

>   HResult=0x80131500
>   Message=Incorrect syntax near the keyword 'Checkpoint'.
>   Source=NHibernate

**Comment by dennisdoomen** [comment]
That's weird. We are using SQL Server, PostgreSQL and SQLite and never ran into this. Are you using some sort of auto-mapping? Because we create explicit maps for all our persistent types.

**Comment by MarcusChamberlain** [comment]
Sorry for the late reply. I'm using FluentNHibernate, but I'm using whatever mapping is setup in the LiquidProjections.NHibernate ExampleHost project.

In that ExampleHost project, there is a file 'ExampleHost.InMemorySqLiteDatabaseBuilder.cs'. I replaced 'new SQLiteConnection' with 'MsSqlConfiguration.MsSql2012'. No other changes apart from switching the connection type.

Is there something else I need to be doing to get LP.N to work with MsSqlServer 2017?

**Comment by dennisdoomen** [comment]
You could add an overriding mapping like https://github.com/liquidprojections/LiquidProjections.NHibernate/blob/9c9a32ef9f7fc74d5da8834627435be167cecb7a/Samples/ExampleHost/Projections/DocumentCountProjection.cs#L64-L70

**Comment by MarcusChamberlain** [comment]
Will do, thanks Dennis.
